spring:
  datasource:
    url: jdbc:postgresql://localhost/lab
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
server:
  port: 9090
