--3

--4
-- ALTER TABLE EMP ADD COLUMN tel_fixed CHAR(10);
-- ALTER TABLE EMP ADD COLUMN tel_mobile CHAR(10);
-- ALTER TABLE EMP ADD CONSTRAINT chk_mobile_phone CHECK(tel_mobile~'06[0-9]{8}$');
-- ALTER TABLE EMP ADD CONSTRAINT chk_mobile_phone CHECK(tel_mobile LIKE '06%');
-- ALTER TABLE EMP DROP COLUMN tel_fixed ;
-- ALTER TABLE EMP DROP COLUMN tel_mobile;
--5
-- ALTER TABLE DEPENDENTS DROP CONSTRAINT fk_dependent_emp;
-- ALTER TABLE DEPENDENTS ADD CONSTRAINT fk_dependent_emp FOREIGN KEY (EMPNO) REFERENCES EMP(EMPNO) ON DELETE CASCADE ON UPDATE CASCADE;
--6
-- CREATE SEQUENCE Sequencedep START WITH 8000 INCREMENT BY 2;
-- INSERT INTO DEPENDENTS VALUES (nextval('Sequencedep'), 'Smith', 'John', 7654);
-- SELECT * FROM EMP WHERE EMPNO = 7654;


-- SELECT * FROM DEPENDENTS;
--PRCTICE2
-- SELECT table_name FROM information_schema.tables where table_schema='public';
-- SELECT * FROM EMP;
-- SELECT * FROM DEPENDENTS;
-- SELECT * FROM DEPT;
-- SELECT * FROM SALGRADE;
-- SELECT * FROM BONUS;

--2.2
-- SELECT * FROM EMP WHERE COMM > SAL;
--2.3
-- SELECT * FROM EMP WHERE  (COALESCE(COMM,0) + SAL) BETWEEN 1200 AND 2000;
--2.4
-- SELECT * FROM EMP WHERE JOB IN ('CLERCK','ANALYST');
--2.5
-- SELECT * FROM EMP WHERE ENAME LIKE 'M%';
--2.6
-- SELECT * FROM EMP WHERE ENAME LIKE '_L%';
--2.7
-- SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERCK') AND DEPTNO = 10 AND SAL >1500;
--2.8
-- SELECT * FROM EMP WHERE COMM IS NULL;
--2.9
-- SELECT * FROM EMP ORDER BY HIREDATE ASC;
--2.10
-- SELECT * FROM EMP ORDER BY JOB DESC, SAL ASC;
--2.11
-- SELECT * FROM DEPT WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMP);
--2.12
-- SELECT * FROM EMP 
--2.13
-- SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'JONES');
--2.14
-- SELECT ENAME, SAL AS INCOME FROM EMP UNION SELECT ENAME, COMM FROM EMP WHERE COMM IS NOT NULL;
--2.15
-- SELECT DISTINCT DEPTNO FROM EMP INTERSECT SELECT DEPTNO FROM DEPT;
--2.16
-- SELECT E.* FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE D.LOC = 'CHICAGO' AND E.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'JONES');
--2.17
-- SELECT E.* FROM EMP E LEFT JOIN EMP B ON E.MGR = B.EMPNO AND B.DEPTNO <> E.DEPTNO;
--2.18
-- SELECT * FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE JOB = 'CLERCK');
--2.19
-- SELECT * FROM EMP WHERE DEPTNO = 10 AND JOB IN(SELECT JOB FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES'));
--2.20
-- SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'JONES') OR SAL > (SELECT SAL FROM EMP WHERE ENAME = 'FORD');
--2.21
-- SELECT * FROM EMP WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO = 2);





